// try { 
//    // program that might throw an exception 
// }  
// on Exception1 { 
//    // code for handling exception 1
// }  
// catch Exception2 { 
//    // code for handling exception 2
// }
void main(){

}